### ISSUE TITLE
type identifiers highlighted with same color as keywords

### ISSUE THREAD

**Issue by gavinking** [jeancharles-roger/ceylon-sublimetext#3]
I don't find it pleasing that type names and keywords both get highlighted in magenta. I think it should be a different color. But I can't seem to find where the color is assigned to `storage.type.ceylon`.

**Comment by jeancharles-roger** [comment]
In sublime text colors are assigned by the themes. In the Monokai types and keywwords colors are different.
In the github context, I guess it's the theme doesn't make difference between `storage.*`and `keyword.*`. Maybe it should be changed, but I don't know to what.

**Comment by jeancharles-roger** [comment]
I've checked from a [Scala](https://github.com/aroben/scala.tmbundle/blob/master/Syntaxes/Scala.tmLanguage) tmLanguage. 
I changed `storage.type.ceylon` to `entity.name.declaration.ceylon`. It should be better.

**Comment by gavinking** [comment]
OK, great, thanks!
